# Generated by Django 4.2.29 on 2026-04-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.URLField(blank=True, max_length=500)),
                ('born', models.CharField(blank=True, max_length=200)),
                ('died', models.CharField(blank=True, max_length=200)),
                ('feast', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('categories', models.ManyToManyField(blank=True, to='core.category')),
                ('saint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.saint')),
            ],
        ),
    ]
