# Generated by Django 4.2.29 on 2026-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='saints/'),
        ),
    ]
